### ISSUE TITLE
How can I actually get datasets?

### ISSUE THREAD

**Issue by NamgyuCho** [ismir/mir-datasets#16]
I wonder how to download datasets for structural segmentation challenge. 

I figured out about RWC. But, what should I do to obtain the others: the MIREX 2009 Collection and MIREX 2012 dataset?

**Comment by ejhumphrey** [comment]
I'm not familiar with those datasets, I'd propose contacting someone who's published on those datasets and see what they advise. If you happen to find a public link for that data, feel free to submit a PR on this collection so that the community can benefit from your sleuthing! I gave the table a look and it doesn't seem that those two MIREX datasets are named there. 

gl!
