### ISSUE TITLE
dataset list page on ismir website is broken

### ISSUE THREAD

**Issue by alastair** [ismir/mir-datasets#20]
This url fails to load: http://www.ismir.net/resources/datasets/
with an error in the console: 
   Failed to load resource: the server responded with a status of 404 ()
   https://ismir.github.io/mir-datasets/assets/js/mir-datasets.js

**Comment by ejhumphrey** [comment]
looked into it and this is now resolved. 

*details*
A way (adjectives withheld) to connect the this repository to the ISMIR website while using static web technologies is for this repository to serve the dataset table as a JS source. This repository achieves this through the following:

* maintain a markdown table here
* render it as JS when modified
* push back to this repository
* serve via github pages

For some reason (maybe yours truly? who can be sure), this repository had been undeployed from github pages. Hooking this back up again fixed the link. I will move the above info to the readme, since it's (a) kind of important and (b) kind of non-obvious.
